site_name: Моя База Знаний
site_url: https://a18091986edu.github.io/my-knowledge-base/
repo_url: https://github.com/a18091986edu/knowledge-base

theme:
  name: materialx
  features:
    - navigation.tabs        # вкладки в главном меню
    - navigation.tabs.sticky # Закрепленные вкладки
    - navigation.prune
    # - navigation.sections    # секции в сайдбаре
    - navigation.expand      # раскрытие текущей секции в сайдбаре
    - navigation.instant     # мгновенная навигация
    - navigation.top         # кнопка "наверх"
    - navigation.tracking    # отслеживание позиции
    - navigation.indexes
    - search.suggest         # подсказки в поиске
    - search.highlight       # подсветка в поиске
    - content.code.copy      # копирование кода
    - content.code.annotate
    # - toc.follow
    # - toc.integrate
    - navigation.path


  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  # - pymdownx.snippets
  - pymdownx.superfences      # для сворачиваемых блоков
  - pymdownx.details          # для сворачиваемых блоков
  - admonition                # для заметок
  - tables
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true  # Для более красивого оформления
  - pymdownx.details  # Для ??? блоков
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Для поддержки include
plugins:
  - search
  - macros:
      include_dir: docs

nav:
  # - Главная: index.md
  
  - DevOps:
    # - devops/devops.md
    - Docker:
      - devops/docker/docker.md
    - Linux: 
      - devops/linux/linux.md

  - ML:
    - CUDA: ml/cuda/cuda.md
    
  
  - Python:
    - python/python.md
    - Веб-фреймворки:
      - FastAPI: python/fastapi/fastapi.md
    - Документирование: 
      - MkDoks: 
        # - python/docs/mkdocs/mkdocs.md
        - Развертаывание: python/docs/mkdocs/mkdocs-deploy.md
        - Написание документации: python/docs/mkdocs/mkdocs-doc.md
    - Пакетные менеджеры: 
      - UV: python/package_managers/uv/uv.md
    - Инструменты: 
      - ruff: python/tools/ruff/ruff.md
    - Глоссарий: glossary/glossary.md
  
  
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
      name: GitHub

extra_css:
  - stylesheets/extra.css


copyright: © 2024 Моя База Знаний